### ISSUE TITLE
Unrecognized function or variable 'match_trajectories'

### ISSUE THREAD

**Issue by elwaaamr** [skousik/RTD_tutorial#1]
Hi,
According to **step1** there is no function called **match_trajectories** in any Matlab directory! in which gave an error: Unrecognized function or variable 'match_trajectories'

**Comment by shaoyifei96** [comment]
Hello,
You need to install the prerequisite for the this package, as in README.

The match_trajectories function is in simulator package.

Thanks for you interest in this work!
