### ISSUE TITLE
Cant find 'get_2D_contour_points' method. 

### ISSUE THREAD

**Issue by michaelaingerman** [skousik/RTD_tutorial#2]
Hello, I'm trying to run step 4 examples, however I keep encountering an issue locating the 'get_2D_contour_points' method. After further searching, it doesn't appear to be explicitly defined anywhere.

**Comment by shaoyifei96** [comment]
Hello, Thanks for your interest in this repo.  This method can be found here.  https://github.com/skvaskov/RTD/blob/master/utility/visualization/get_2D_contour_points.m  
Please look at the readme to install all the dependencies~

**Comment by michaelaingerman** [comment]
Thank you!
